version: "3"

services:
  metabase:
    restart: unless-stopped
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=<db_name>
      - MB_DB_PORT=5432
      - MB_DB_USER=<user>
      - MB_DB_PASS=<pass>
      - MB_DB_HOST=<host>
    volumes:
      - ./metabase:/metabase-data

  postgres:
    restart: unless-stopped
    image: postgres
    container_name: metabase-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=<db_name>
      - POSTGRES_USER=<user>
      - POSTGRES_PASSWORD=<password>
    volumes:
      - ./postgres:/var/lib/postgresql/data
