# Stage 1: Build
FROM node:18-alpine as builder

# Set workdir
WORKDIR /usr/src

# Set build time variables, reading from build-args
ARG BASE_URL=http://localhost:3000/
ARG NODE_ENV=development

# Map the build time environment to environment variables
ENV BASE_URL=$BASE_URL
ENV NODE_ENV=$NODE_ENV

# Copy files
COPY . .

# Install frontend dependencies and build
RUN npm install --prefer-offline

# Conditional build command
RUN npm run build

# Step 2: Serve
FROM nginx:alpine

# Set workdir
WORKDIR /usr/src/app

COPY --from=builder /usr/src/build/ /usr/share/nginx/html/
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

# Expose Port for Nginx
EXPOSE 80

CMD ["nginx","-g","daemon off;"]