version: "3"
services:
  node-exporter:
    restart: unless-stopped
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    command: --path.rootfs=/host
    network_mode: "host"
    pid: "host"
    volumes:
      - /:/host:ro,rslave
    ports:
      - "9100:9100"

  prometheus:
    restart: unless-stopped
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - ./data:/prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.config.file=/etc/prometheus/web.yml
