version: "3"

services:
  prometheus:
    restart: unless-stopped
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus-config:/etc/prometheus
      - ./prometheus-data:/prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.config.file=/etc/prometheus/web.yml
