version: "3.1"

services:
  mongodb:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db
      - ./mongodb:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: <your_root_username>
      MONGO_INITDB_ROOT_PASSWORD: <your_root_password>
