server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

# Modify the Loki API URL
clients:
  - url: http://127.0.0.1:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          # Modify the targets
          - localhost
        labels:
          # Modify the jobs
          job: nginx-access-logs
          __path__: /var/log/nginx/access.log
