version: "3.8"
services:
  redis-staging:
    container_name: redis-staging
    image: redis:5.0.2-alpine
    restart: always
    ports:
      - "6379:6379"
    # Modify the credentials
    command: redis-server --save 20 1 --loglevel warning --requirepass <your_redis_password>
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local
